# Site settings
title: Blog.rino0601
email: rino0601@naver.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a blog. The Owner of this blog is not familiar with using jekyll yet. So it looks poor. But I hope you understand.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rino0601.github.io" # the base hostname & protocol for your site
#twitter_username: I don't use twitter.
github_username:  rino0601

# Build settings
markdown: kramdown
